### ISSUE TITLE
Append node

### ISSUE THREAD

**Issue by promontis** [vpenades/SharpGLTF#10]
Hi @vpenades !

What's the reasoning for building the node hierarchy exclusively via `CreateNode()`?

I'm traversing my application's DOM depth first, and I would like to create nodes independently from it's parent.

So say we have a DOM like this:
```
A
- B
   - C
```

I would like to:
- create node C
- create node B, and add node C to its children
- create node A, and add node B to its children

So, I need something like `AppendNode()`, which would append the node to a node's children.

Is this something we could add?

**Comment by vpenades** [comment]
If you notice, it's not only in nodes, I try to avoid to create isolated gltf objects as much as possible across the whole API.

It could be possible to include an Ardmore, which would also require to add a CreateLogicalNode at root level.

The reasons are these:

If I allow isolated objects to be created, I need to prevent, somehow, that a Node.created in a model is not added in the scene of a different model.

Even if the new node is owned by the model, there's lots of breaking use cases that need to be checked:
Self references
Circular dependencies
The root node in a scene, added to the child in another scene

So for now, the best way to ensure the created tree is correct, is with the current API

**Comment by promontis** [comment]
Understandable :) I will try to work around this... will let you know if it works out!

**Comment by promontis** [comment]
It works! I now output to an intermediate object, which implements an interface that can be used to generate nodes by passing along a parent node.

**Comment by vpenades** [comment]
Notice that both Scene and Node already implement such interface, see `IVisualNodeContainer`

**Comment by promontis** [comment]
Thanks for the tip! Will try if this interface works as well 👍
