### ISSUE TITLE
Mesh Skinning support

### ISSUE THREAD

**Issue by pixtur** [vpenades/SharpGLTF#103]
I'm working an integration of SharpGltf into https://github.com/still-scene/t3 
So far, I'm able to fetch static meshes and attributes. Does the core library also support skinning? I.e. morphing the vertex position and normals according to characters animation provided inside an glft-file?

**Comment by vpenades** [comment]
Yes.

I suggest you to look into the SharpGLTF.Runtime namespace and associated unit tests. In there you can find classes and infrastructure that feeds all the transforms required for animations.

**Comment by pixtur** [comment]
That sounds great! Thanks.
