### ISSUE TITLE
`JsonContent.Serialize()` throw `System.NullReferenceException` when some collection count = 0

### ISSUE THREAD

**Issue by LovingEvil** [vpenades/SharpGLTF#105]
sharpgltf.core.1.0.0-alpha0023
`JsonContent.Serialize(object)`
object with empty collection - throw `System.NullReferenceException`.
object with collection = null - no Exception.

Approximate object structure:
- object
    - Collcection
        - SubCollection1 = new List<SomeClass>(); *- throw `System.NullReferenceException`.*
        - SubCollection2 = null; *- no Exception.*

Serialization is executed without options.

`StackTrace:
   at SharpGLTF.IO._JsonArray.TryClone(IEnumerable collection)`

Is this intended behavior or is there something wrong?

**Comment by vpenades** [comment]
Yes, the glTF schema forbids empty collections as they're considered a waste of resources.  Empty arrays should be replaced by nulls.

**Comment by LovingEvil** [comment]
Ok. I have to keep track of this in my code? ShaprGLTF doesn't have collection preprocessing tools? Some best practices in this case... 🙄

**Comment by vpenades** [comment]
Internally, the library does handle these cases _for the main schema_  but I am guessing your having these issues with the Extras property?

**Comment by LovingEvil** [comment]
Yes, and I did not immediately understand what the problem was. The sources for collecting data for writing to extras are different, empty collections have not been encountered before, and everything worked. Now I am checking all collections from the object before `JsonContent.Serialize(object)`.

Like this:
```C#
foreach (item in object)
{
  if (item.Collection.Count == 0)
  {
      item.Collection = null;
  }

  // other collections checks (with subCollections)
}
```

**Comment by vpenades** [comment]
The problem with json serialization is that the whole architecture is designed to _expect a schema_; everything in glTF works with a schema, except for the extras field.  So all the provisions I made for the main schema do not apply for extras.

So for now you should check for empty collections in the extras field. I'll try to find a better solution for the next version

**Comment by LovingEvil** [comment]
Thanks for the explanation and your work on sharpGLTF!

**Comment by vpenades** [comment]
fixed in [this commit](https://github.com/vpenades/SharpGLTF/commit/714c4bffcd0f8a2b390fd52e077520395bf6f7c4)
