### ISSUE TITLE
.NET 6 Upgrade/Support

### ISSUE THREAD

**Issue by RagingKore** [vpenades/SharpGLTF#108]
.NET 6 is just around the corner and with its all around performance optimizations plus new apis, SharpGLTF could strongly benefit from this. Not to mention that it is the inevitable future.

I'm more than willing to contribute and push a PR that bumps the framework. 

Would this be of interest @vpenades

**Comment by vpenades** [comment]
The current libraries already target Net5, which is fully compatible with Net6 in terms of runtime features and performance.

Also, SharpGLTF aims for compatibility with as many target platforms as possible... so, adding Net6 as a target platform is not a problem, but the other target platforms must be kept.

Anyway, I would like to know which kind of inprovements you had in mind

**Comment by vpenades** [comment]
project has been updated to support net6.
