### ISSUE TITLE
There is any way to apply trasnform matrix set model?

### ISSUE THREAD

**Issue by learnerandtrainer** [vpenades/SharpGLTF#110]
Hi,
I have a b3dm model that created by sharp gltf and one json file that cantains transform parameter for cesium to load my b3dm.
whenI want to preview every think is okey. But I want to set my transform parameter into b3dm(glb) itself because cesium transform my other child geometries using root and childs parameters. I used model.ApplyBasisTransform function but it doesnt work. Is there any way to transform model by trasnform matrix?
Here my example files
[157146.zip](https://github.com/vpenades/SharpGLTF/files/7353789/157146.zip)

**Comment by vpenades** [comment]
I think the best approach is this:

You have to "transfer" the mesh resources from one glTF to another, applying a mesh transform in between.

there is a unit test that does something like that [here](https://github.com/vpenades/SharpGLTF/blob/9ca62b911441c89b2f6048cfd44aef7ca9b79889/tests/SharpGLTF.Toolkit.Tests/Scenes/SceneBuilderTests.cs#L603)

Essentially, you create a new SceneBuilder, and you add the meshes from the source glTF, applying a transform matrix, Then, you can save the SceneBuilder as a glTF

**Comment by learnerandtrainer** [comment]
Hi vpenades, I cant combine them in a new one because they have different trasnform values. for this scenario I have to trasnform geometries by their transform parameter before save them as gltf. I dont know cesium how calculate geometries by transform at runtime. I asked them but didnt get answer yet. I suppose that it is a bit complex. 
But I find new solution to merge them without calculating geometries by transform. I took center point of 15 level for 15,17,18 levels. And then translated all levels by this center point . This helped identify a single conversion for all levels . After that I could add levels as upper level child and set trasnform to only root element. 
Thank you for answers
