### ISSUE TITLE
How do I integrate multiple GLBS

### ISSUE THREAD

**Issue by YJinzz** [vpenades/SharpGLTF#114]
I have multiple GLB files, I need to consolidate them into a GLB file, and write my related configuration items (setting.Json) into the integrated GLB file, how should I do  ？     Can you give me an example if you have time?  This is my email address: YJinworker@gmail.com thank you very much

**Comment by vpenades** [comment]
There's a closed issue discussing it: #79

**Comment by YJinzz** [comment]
Thank you for the response  It did merge into a GLB file but the internal structure was wrong and the front end could not parse 
![1](https://user-images.githubusercontent.com/79623396/143412936-8a4d540e-e1d5-4fee-be1f-807f987d91bc.jpg)
@vpenades

**Comment by vpenades** [comment]
> but the internal structure was wrong and the front end could not parse

- In what sense?
- is the GLB invalid?
- Does the ok.glb load in windows gltf viewer?
- which error gives you on load?

**Comment by vpenades** [comment]
Without more context or a reproducible example I can't help, so I'm closing this issue.... feel free to reopen it if you need help
