### ISSUE TITLE
Merge Meshes

### ISSUE THREAD

**Issue by famda** [vpenades/SharpGLTF#126]
Hi,
Is is possible to merge meshes and the materials of those meshes as one?

Could you help, please?

Thanks in advance.

**Comment by vpenades** [comment]
https://github.com/vpenades/SharpGLTF/issues/104

**Comment by famda** [comment]
Hi,
Thank you for the quick reply but, unfortunatly, that is not what I'm looking for.
This video explains the problem that I'm not being able to solve so far.

https://youtu.be/6APzUgckV7U

The idea is to have 1 model with multiple meshes and be able to merge those meshes together as 1.

Thanks in advance.

**Comment by vpenades** [comment]
if you simply want to "merge" multiple meshes into one, you must create a new MeshBuilder and aggregate the vertices of the source meshes into that MeshBuilder.

Notice that "merging" meshes is not the same as fusing the meshes with a boolean operation (add, subtract, etc) which is not supported by the library

**Comment by famda** [comment]
I can try that and see what happens. 😀

I'm not sure I understand the fusing part.
Sorry about that, I'm still new to this 3d world.

Thanks.
