### ISSUE TITLE
Morph target animation using MorphTargetBuilder

### ISSUE THREAD

**Issue by vermadas** [vpenades/SharpGLTF#127]
Hi there,

I'm trying to understand how to set up a morph target animation. Looking at this test:
https://github.com/vpenades/SharpGLTF/blob/f6e5ebd1f3edb5ab47dbac6e6f7042dedb7f8980/tests/SharpGLTF.Toolkit.Tests/Scenes/SceneBuilderTests.cs#L443

Looking at the code, I believe the result should show the second pink cube moving up 1 meter and then back down. However, when I run the test the result does not have any animation.

It's quite possible I'm missing something. Thanks for your time.

**Comment by vpenades** [comment]
You're right, it seems it's broken, I'll look for a solution

**Comment by vermadas** [comment]
Excellent, that fixed the issue for me. Thanks!
