### ISSUE TITLE
MonoScene?

### ISSUE THREAD

**Issue by juliand665** [vpenades/SharpGLTF#128]
Hey, I'm aware this isn't quite the right place to ask, but you've archived the MonoScene repo so I can't ask there. That's actually what I'm asking about: did you decide to halt development of MonoScene? We're currently creating a game for university and one of my team members added your library to our project, so it'd be nice to know what the state of things is there :)

**Comment by vpenades** [comment]
I would not say "halted forever" but definitely frozen. And unless there's _dramatic changes_ in MonoGame's project's maintenance, it will remain that way for the time being.

Simply put, MonoGame's 3D API has not received any relevant update for the last 2 years, most attempts to fix things have been rejected or left waiting for review/merge for months/years, and even if bug fixes are merged, no new nuget packages have been published for a long long time. Also, at work we've been required to support VR headsets, which is something that takes MonoGame out of the equation for us.

So it's difficult from our side to justify investing time in a framework (monoScene) that depends on a library (MonoGame) with an outdated 3D API and with no prospect of improving it.

MonoGame is still a great framework for making 2D games, which is for what devs are using it.... but for 3D, it simply doesn't cut the bread anymore.

Anyway, feel free to use/fork MonoScene if you find it useful!

**Comment by juliand665** [comment]
I see, thanks so much for responding! It's a bit awkward now that it's archived, but maybe it would make sense to leave something like this as a note on top of the repo's readme?

We're working on a 3D game, but _probably_ won't need super-advanced or modern stuff, and we're required to use MonoGame anyway. We've added MonoScene as projects in our solution, so I bet we can make any updates we feel are necessary. Thanks for all you've done!
