### ISSUE TITLE
Test 'CreateSceneWithSpecularGlossinessExtension' failing

### ISSUE THREAD

**Issue by bertt** [vpenades/SharpGLTF#13]
Test 'CreateSceneWithSpecularGlossinessExtension' is failing, think because images are missing (like WaterBottle_normal.png)

**Comment by vpenades** [comment]
Ah, yes, you're right

That test requires to download the reference files before running the tests.

Reference files are automatically downloaded by other tests (it takes several minutes to download, depending on your connection), but the test you mention did not download them, I'll fix it!

**Comment by bertt** [comment]
Thanks, works now!
