### ISSUE TITLE
Export Obj

### ISSUE THREAD

**Issue by Omega1975** [vpenades/SharpGLTF#131]
I have created an Obj to gltf / glb converter which copies the data on vertices, textures and normals in the data structures of the sharpgltf library without modification. With several objects the export is correct but I have some problem with a model whose geometry is correct but not the texture mapping.
How can I correct the mapping?
[DONNA2.zip](https://github.com/vpenades/SharpGLTF/files/8407914/DONNA2.zip)

**Comment by vpenades** [comment]
your model loads just fine in windows viewer as you can see here:
![imagen](https://user-images.githubusercontent.com/5433822/161509481-2ffe3042-1b40-473e-9fab-ccddbc676405.png)

So the problem is in your side, not mine.

**Comment by Omega1975** [comment]
yes, I agree but how can I correct the texture mapping to get the same result. I am attaching the export in glb format
[base.zip](https://github.com/vpenades/SharpGLTF/files/8408437/base.zip)
.

**Comment by vpenades** [comment]
Wavefront OBJ has the texture V coordinate inverted, that is, from bottom to top.

Please, learn about the formats you use before using them.

**Comment by Omega1975** [comment]
Thank you very much.
