### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by Omega1975** [vpenades/SharpGLTF#134]
I would like to load a gltb file, replace the texture of a material and save it.
I tried replacing the texture with the following code, which produces no errors but creates an invalid gltf file.

```c#
foreach (SharpGLTF.Schema2.Material mm in model.LogicalMaterials)
            {
                
                foreach (SharpGLTF.Schema2.MaterialChannel ch in mm.Channels)
                {
              
              
                    if (ch.Texture != null)
                    {
                        
                        if ((ch.Key == "BaseColor")) {                            
                            int tx = ch.TextureCoordinate;
                            SharpGLTF.Schema2.Image imm = model.CreateImage("LOGO");
                            imm.Content = new MemoryImage("C:\\TEMP\\logo.png"); 
                            ch.SetTexture(tx, imm, null, ch.TextureSampler.WrapS, ch.TextureSampler.WrapT, ch.TextureSampler.MinFilter, ch.TextureSampler.MagFilter);
                        }                        
                    }                    
                }                
            }
	    
	 WriteSettings ws = new WriteSettings();         
         ws.ImageWriting = ResourceWriteMode.SatelliteFile;
         model.SaveGLTF(filename, ws);
```

Am I doing everything wrong? How can i replace the texture?

**Comment by Omega1975** [comment]
no one can help me ?

**Comment by vpenades** [comment]
I tested your code in a random model and everything went just fine.

So either your model is wrong, or you didn't explain correctly want you want to achieve, or you misunderstood how the API works and you expected something different than what the API actually does.

**Comment by Omega1975** [comment]
The model I use I validated with glTF-Validator.
If I use the code I posted earlier the model I get is invalid.

I solved differently, below the code 

//Load Image
public byte[] imageToByteArray(System.Drawing.Image imageIn)
        {
            LocalErrorMessages = "";
            try
            {
                MemoryStream ms = new MemoryStream();
                imageIn.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                return ms.ToArray();
            }
            catch (Exception ex)
            {
                LocalErrorMessages = "\r\n" + "Utils_glTF.imageToByteArray" + ex.Message.ToString() + "\r\n" + ex.StackTrace.ToString();
                Console.Write(LocalErrorMessages);
                return null;
            }            
        }


        /// <summary>
        /// Texture substitution
        /// </summary>
        /// <param name="dMaterial">dictionary  <material index, texture filename></param>
        /// <returns></returns>
        public bool ModifyTexture(IDictionary<int, string> dMaterial) {
            LocalErrorMessages = "";
            try
            {
                if (model != null) {
                    int i = 0;
                    foreach (SharpGLTF.Schema2.Material mm in model.LogicalMaterials) {
                        if (dMaterial.ContainsKey(i)) {
                            MaterialBuilder mb = mm.ToMaterialBuilder();
                            mb.WithChannelImage(KnownChannel.BaseColor, new MemoryImage(imageToByteArray(new Bitmap(dMaterial[0]))));
                        }                        
                        i++;
                    }
                }                
                return true;
            }
            catch (Exception ex)
            {
                LocalErrorMessages = "\r\n" + "Utils_glTF.ModifyTexture" + ex.Message.ToString() + "\r\n" + ex.StackTrace.ToString();
                Console.Write(LocalErrorMessages);
                return false;
            }
        }
