### ISSUE TITLE
Question: Move nuget package to nuget.org

### ISSUE THREAD

**Issue by deccer** [vpenades/SharpGLTF#135]
Hi there,

is it possible to move the nuget hosting from github over to nuget.org?
Its a total pain in the butt to get nuget package sources working when they sit on github.

Cheers.

**Comment by vpenades** [comment]
The nugets are published regularly at nuget.org, and links are provided in the front page of this repository, as in the releases.

So you probably are using an outdated nuget package.

Please, use the packages at nuget.org, and if your other issues are due to using the wrong package, close them

**Comment by deccer** [comment]
Oh boy, I am blind!

**Comment by deccer** [comment]
The other 2 problems persist.

I was using the sources directly.

However I will close this issue.
