### ISSUE TITLE
how to add scene with both translation and rotation

### ISSUE THREAD

**Issue by kkbandaru** [vpenades/SharpGLTF#147]
One more question
 
how to add the scene using scenebuilder with both Translation and rotation.

merged.AddScene(terrain, Matrix4x4.CreateTranslation(0,0,0));

**Comment by kkbandaru** [comment]
thanks, i am developing apps in babylonjs and unreal for long time, this Matrix4x4 abstracted for developers , any how after your message i started understanding about Matrix4x4. 

one more questions, i want to to set the texture base color for material with uScale and VScale 
i am trying to set like this, how to set Uscale and VScale
materialBuilder.WithChannelImage("BaseColor", basePath + filename);

**Comment by vpenades** [comment]
https://github.com/vpenades/SharpGLTF/blob/acd6f8a7345987f1e50eaaf3b26d213d9a78998c/tests/SharpGLTF.Toolkit.Tests/Materials/MaterialBuilderTests.cs#L138
