### ISSUE TITLE
System.ArgumentException: ' Parameter name: _Slicer' - No Items on the IndexAccessor

### ISSUE THREAD

**Issue by gotoarchi** [vpenades/SharpGLTF#151]
https://github.com/vpenades/SharpGLTF/blob/fdcd1b2a453472358ee3f5aa4c6edb0f329dd21d/src/SharpGLTF.Core/Memory/MemoryAccessor.cs#L428

When we load the following sample GLTF https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy/glTF we are getting an exception on L428 when trying to access the Items of the IndexAccessor for most of the LogicalMeshes. Please look on the image under:

![SharpGLTF](https://user-images.githubusercontent.com/80472813/193478337-284b1394-f962-494e-b5a5-da49b41934c7.png)

**Comment by vpenades** [comment]
What was failing was the debugger proxy that was incorrectly displaying index data as vertex data. This has no effect in production code.

In case you want to get the index data from an accessor,  use `.AsIndicesArray();`
