### ISSUE TITLE
Reading meshes

### ISSUE THREAD

**Issue by gotoarchi** [vpenades/SharpGLTF#152]
Saludos Vicente

Thanks for your great library.

We are reading a GLTF trying to find the final (global?) coordinates of the positon vertices. We looping the nodes->meshes and came across the Local Transform object and matrix. Is there any example that shows any methods that help transforming the vertices across their absolute final location. I understand that being a child you inherit transformations, but I am stuck in the transformation process.

Any example or documentation would be highly appreciated.

**Comment by bertt** [comment]
Hi maybe Toolkit .EvaluateTriangles is what you are looking for.

**Comment by gotoarchi** [comment]
I am afraid I need a very simple example to understand the implementation of the TRS transformation to the final coordinate.

**Comment by vpenades** [comment]
Every node also has a world matrix.

You just need to multiply the vertices of the mesh by the world matrix of the node containing the mesh.

**Comment by vpenades** [comment]
vector x matrix multiplication is handled by the System.Numerics types, if you're new to them I would suggest you to learn about their types, because they're widely used along all the library. There's plenty of documentation and examples about vector3 and matrix4x4 around.
