### ISSUE TITLE
Valid gltf asset throwing error.

### ISSUE THREAD

**Issue by gotoarchi** [vpenades/SharpGLTF#158]
https://github.com/vpenades/SharpGLTF/blob/66a90e9b56a5e0a05f474f5de13465819ca6679d/src/SharpGLTF.Core/Schema2/gltf.MeshPrimitive.cs#L409

A gltf validated with the Khronos gltf validator is throwing an error here:

Please have a look on the attached zip file with the tested file.
https://tmpfiles.org/dl/211804/gltfbin.zip

**Comment by vpenades** [comment]
link reports File Not Found.

**Comment by gotoarchi** [comment]
lets try again:

https://we.tl/t-j3AtGYY9Sx
