### ISSUE TITLE
Validating file says file is valid but returns UNSUPPORTED_EXTENSION error message 

### ISSUE THREAD

**Issue by pedram-keshava** [vpenades/SharpGLTF#159]
So I try to validate the attached file here - https://github.khronos.org/glTF-Validator/

![image](https://user-images.githubusercontent.com/117511072/200112691-f95ef7f0-790f-4d9a-989c-30eced816605.png)

That says, file is valid but still it also returns the error message,

"code": "UNSUPPORTED_EXTENSION",
"message": "Cannot validate an extension as it is not supported by the validator: 'KHR_draco_mesh_compression'.",

Is it known issue? Please help. 

Note: I have also attached sample file I am using to validate.

Thanks.

[Sample_unhandle.zip](https://github.com/vpenades/SharpGLTF/files/9943455/Sample_unhandle.zip)

**Comment by vpenades** [comment]
Draco compressed glTF files are not supported by SharpGLTF, see #44
