### ISSUE TITLE
[HELP] Can not add lights to a scene

### ISSUE THREAD

**Issue by 11bitbadger** [vpenades/SharpGLTF#161]
A `SceneBuilder` has a method `AddLight`, which takes a `LightBuilder` but I can not create a `LightBuilder`.
I assume if I wanted to add a Directional light I should be using `LightBuilder.Directional()` but there is no public constructor.

How do I add a new light to a scene?

**Comment by vpenades** [comment]
You're right; the current API allows importing a lights from an existing glTF but it doesn't allow creating lights from scratch.

I'll add public APIs for it, stay tuned.
