### ISSUE TITLE
Morph Target / Shape Keys Support? 

### ISSUE THREAD

**Issue by GlitcherOG** [vpenades/SharpGLTF#163]
I was working on a model exporter/importer to convert some ps2 game models to GLTF and back and I was wondering whether or not if there is any morph target/shape key support in the works as some of my work hinges on that.

**Comment by vpenades** [comment]
The library does support morph targets, and there's other people already exporting morph target animation with SharpGLTF.

But I must say that morph target animation is, by far, the most complex feature of the library and handling morph targets with SharpGLTF is difficult to say the least.

The unit tests of the library serve the double purpose of testing the library and also test multiple features, including morph targets.

**Comment by GlitcherOG** [comment]
Must of missed it when looking the library does confuse me sometimes, Do you know of any examples on trying to add morph targets when making models?

**Comment by vpenades** [comment]
As I said, in the unit tests you can find some examples.

Like here: https://github.com/vpenades/SharpGLTF/blob/master/tests/SharpGLTF.ThirdParty.Tests/AceCebovTests.cs

**Comment by GlitcherOG** [comment]
Lol I really am blind, thanks for the help
