### ISSUE TITLE
[BUG] WriteSettings.MergeBuffers is ignored for both GLTF and GLB export formats.

### ISSUE THREAD

**Issue by MeltyPlayer** [vpenades/SharpGLTF#165]
**Describe the bug**
When trying to export a model root via `modelRoot.Save(filePath, writeSettings)` as a GLTF or GLB file, WriteSettings.MergeBuffers is ignored in recent releases of SharpGLTF. 

This is a blocker for me to update to newer versions since some of the models I'm trying to export are enormous, and SharpGLTF will consistently throw OutOfMemoryExceptions in 32-bit applications unless MergeBuffers is set to false.

It appears that MergeBuffers is always set to true within `WithTextSettings()` and `WithBinarySettings()`--is this intended? In previous versions, this was not the case for GLTF files, allowing me to export large files as GLTF. I *was* experiencing this issue back then for GLB files, though.

**To Reproduce**
This happens consistently when I try to call `modelRoot.Save(filePath, writeSettings)` for a filePath ending in `.gltf` or `.glb`. It appears that this is because `Save()` internally calls `SaveGLB()` or `SaveGLTF()`, which both override the WriteSettings that were passed in by calling `WithBinarySettings()`/`WithTextSettings()`. 

**please complete the following information:**
 - SharpGLTF Version: Alpha-027

**Comment by MeltyPlayer** [comment]
Ah whoops, forgot to include the code locations:

*`SaveGLB()`/`SaveGLTF()`:*
https://github.com/vpenades/SharpGLTF/blob/1bfe321a34347ba95f2cc1f1e5df993db60e7856/src/SharpGLTF.Core/Schema2/Serialization.WriteSettings.cs#L173-L211

*`WithTextSettings()`/`WithBinarySettings()`:*
https://github.com/vpenades/SharpGLTF/blob/1bfe321a34347ba95f2cc1f1e5df993db60e7856/src/SharpGLTF.Core/Schema2/Serialization.WriteContext.cs#L105-L127

**Comment by vpenades** [comment]
Could you open a specific PR adding a test case here?

https://github.com/vpenades/SharpGLTF/tree/master/tests/SharpGLTF.ThirdParty.Tests

It will help me track down the bug and ensure it doesn't break again,

**Comment by MeltyPlayer** [comment]
Ah, that sounds good. Thanks for the quick response!

**Comment by vpenades** [comment]
I've uploaded the changes a while ago.

Let me know if it fixes you problem

**Comment by MeltyPlayer** [comment]
Looks good, thanks for fixing this!
