### ISSUE TITLE
[iOS] Does it have support for MAUI cross platform

### ISSUE THREAD

**Issue by akycdi** [vpenades/SharpGLTF#170]
I just want to know if it works in WIN,ANDROID,iOS,MAC
If not can you guys suggest any other

**Comment by vpenades** [comment]
The library is cross platform.

At the very least I have tested it on Windows and Android, but it should work on other platforms.

About MAUI, SharpGLTF is a pure processing library. it does not provide any rendering services by itself.

If what you want is to display a glTF model on a cross platform MAUI control, I don't think MAUI supports 3d graphics yet.

See these:

https://github.com/dotnet/maui/discussions/129
https://github.com/dotnet/maui/discussions/196

**Comment by akycdi** [comment]
Can you suggest any other ways to render GLTF in MAUI for all cross platform without changing it to Blazor Hybrid.
I got a way, is to use TheeJS or BabylonJS with blazor.

**Comment by vpenades** [comment]
If you've been able to embed ThreeJS and BabylonJS,  I think your best chance is to use a MAUI web control, and embed an html page with ThreeJS inside the web control.

Any other option, like using Veldrid or any other graphics engine means you have to write scene logic, lights, shadows, shaders and much more on your own, which is months of work. (And that's probably why there's no control able to do that, yet)
