### ISSUE TITLE
Release version of SharpGLTF nuget

### ISSUE THREAD

**Issue by ansvtrannam** [vpenades/SharpGLTF#181]
Hello vpenades! 

Thank you for your good job.

I'm very interesting in SharpGLTF. I would like to know do you plan to publish a release version of SharpGLTF nuget? (I mean a SharpGLTF.Toolkit.1.0.0 without the alpha suffix)?

Regards.

**Comment by vpenades** [comment]
Well...  to tell the truth, the release/prerelease thing is more a convention than anything else;  and currently SharpGLTF is more mature than many libraries around that state they're release, so if your worry is about whether SharpGLTF is ready for production or not, it is.

Another reason because I keep nuget versions in pre-release is because as glTF standard keeps maturing, I am forced to do breaking changes in the API.... so in a way, keeping the nugets in pre-release is a way of saying: "I can break the API between versions without notice"

It is true that I could switch to release versions, but in practice, it would not change much compared to the way packages are released now, other than the naming convention.

**Comment by vtrannam** [comment]
The reason that we would like a release version:
- We know that features in that version are matured enough to be integrated in the product version
- And it will remove this build  [NuGet Warning NU510](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5104): 
> "_A stable release of a package should not have a prerelease dependency...._

Therefore, changing the [semantic versioning](https://semver.org/) of SharpGLTF will help a lot to decide to integrate it in product side.

**Comment by vpenades** [comment]
Publishing a release is just a matter of changing the naming convention of the semver, but I need some time to review everything and be sure everything's fine.

There *will be* a release nuget at some point, but I can't really tell when it will happen.

**Comment by vtrannam** [comment]
I'm looking forward to the release version then. Thanks a lot.

**Comment by mzh3511** [comment]
@vpenades 
I noticed that there are large changes after the `alpha0030`, do you plan to publish a new alpha version?

**Comment by vpenades** [comment]
not yet, I'm awaiting for some contributors PR changes to be completed and merged.

**Comment by mzh3511** [comment]
Thank you for your reply

**Comment by gregmarr** [comment]
That's good to hear.  We are eagerly awaiting the release using System.Text.Json v8!

**Comment by pixtur** [comment]
I'm really looking forward to an updated release, too.

**Comment by vpenades** [comment]
Still polishing the Tiles3D extension.

Hopefully, we'll be able to publish new packages sometime next week.

**Comment by ilCosmico** [comment]
Hello @vpenades,

A release version would solve a problem with non-SDK projects as reported [here](https://developercommunity.visualstudio.com/t/NuGet-Pre-Release-Dependency-Resolution/10620484).

I hope you reconsider the option to publish it, thanks.

**Comment by vpenades** [comment]
Last release left me exhausted, I didn't even have time to author a proper release tag, so I'm taking a small break.

The plan has always been to release a full version, what I don't want is to release a 1.0.0 version to immediately release a 1.0.1 version 5 days later. This last release has been huge, so I'm waiting for small issues to pile up, fix them, and finally release a full version.

But I don't know when that will happen, I'm full hands at work.

**Comment by ilCosmico** [comment]
I understand and firstly I want to thank you for the great work.

Anyway, in active library development, releasing multiple versions is a norm to fix bugs or enhance features. Publishing version 1.0.0 is an important milestone, not an endpoint. It's vital to embrace the inevitability of future updates, like version 1.0.1, as part of continuous improvement. It’s all part of the journey to make the library better 😉

**Comment by vpenades** [comment]
Version 1.0.0  has been published 👍
