### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by DrEight** [vpenades/SharpGLTF#190]
Hello,
I'm trying to write a converter from GLB to FBX. Do you have an example on how I can traverse the scene?

**Comment by vpenades** [comment]
In SharpGLTF, the section that handles scene traversal is in the Runtime namespace, which in the latest release, I refactored into its own library called SharpGLTF.Runtime

You're not required to use the library if you want to do your own scene traversal, but you can take a look at the library and see how it works.

The method you mighty be interested is [this one](https://github.com/vpenades/SharpGLTF/blob/9009fe9daa9bbbb25656ad9dc8c05b5fcfa9adaa/src/SharpGLTF.Runtime/Runtime/SceneTemplate.cs#L24)
