### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by NiV-L-A** [vpenades/SharpGLTF#192]
Hi there!
I wanted to join the discord server for this repository, but I noticed that the invite link (https://discord.gg/y9mnJQY) listed in the main README.md (https://github.com/vpenades/SharpGLTF/blob/master/README.md) is invalid/expired.
Is it possible to gain a new invite link to the server?
Thank you in advance.

**Comment by vpenades** [comment]
sure, the new link is here: https://discord.gg/ecGAbsUDbB
