### ISSUE TITLE
By default _offsetDefault set to 1,1 but it should be 0,0

### ISSUE THREAD

**Issue by gleblebedev** [vpenades/SharpGLTF#21]
at src/SharpGLTF.Core/Schema2/Generated/ext.TextureTransform.g.cs

private static readonly Vector2 _offsetDefault = Vector2.One;

should be 

private static readonly Vector2 _offsetDefault = Vector2.Zero;

spec: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform

**Comment by vpenades** [comment]
Thanks, I've fixed it in the code generation side.
