### ISSUE TITLE
AttenuationDistance incorrect default value

### ISSUE THREAD

**Issue by BoyBaykiller** [vpenades/SharpGLTF#215]
https://github.com/vpenades/SharpGLTF/blob/7744baca9425c537513300887c752e074f338671/src/SharpGLTF.Toolkit/Materials/MaterialEnums.cs#L192

By [KHR_materials_volume](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume#properties), shouldn't the default value of AttenuationDistance be set to `float.PositiveInfinity`? It currently is 0.0 which I think is incorrect.

**Comment by vpenades** [comment]
I think you're right, I'll fix the code to the correct values.
