### ISSUE TITLE
[BUG] Extras data lost during load

### ISSUE THREAD

**Issue by gentilinigm** [vpenades/SharpGLTF#216]
**Describe the bug**
Any `Extras` data of the entities is lost during the load operation, resulting in null fields.

**To Reproduce**
Import the attached model: [gh216.zip](https://github.com/vpenades/SharpGLTF/files/14039751/gh216.zip)

`SharpGLTF.Schema2.ModelRoot.Load("test.gltf");`

And check the 'Extras' property of the meshes / nodes.

The attached model is a very simple .gltf file with the following structure:
```
node
├── mesh (mesh1)
└── node (br1)
    ├── mesh (meshbr1)
    └── node
        └── mesh (meshbr2)
```
Where the value inside brackets is the relative Extras data.

**please complete the following information:**
 - OS: Windows 10
 - SharpGLTF Version: From Source 6a7a68b

**Comment by vpenades** [comment]
looking into it...

**Comment by vpenades** [comment]
Are you sure the extras are not imported? I can see the extras being correctly imported:

![imagen](https://github.com/vpenades/SharpGLTF/assets/5433822/3eadf2e8-59c7-458a-bbc1-c76dc2d9fcd8)

**Comment by gentilinigm** [comment]
I was checking VS watches and they were all null, but accessing the properties works and they are populated.
Its an error on my end, very sorry for wasting your time.

You can close/delete the issue.
Thank you
