### ISSUE TITLE
Satellite image file name incorrect when the gltf file contains extra dot

### ISSUE THREAD

**Issue by mzh3511** [vpenades/SharpGLTF#217]
Given a gltf file name: `Building 1_Prediction_WiFi 802.11n - 2.4GHz - 20MHz_RSSI by floor.gltf`, the gltf only has one image, 
Expected image file name: `Building 1_Prediction_WiFi 802.11n - 2.4GHz - 20MHz_RSSI by floor.png`
Actual: `Building 1_Prediction_WiFi 802.11n - 2.png`

The reason:
when write the json by `WriteTextSchema2` method, the `baseName` does not include the extension
![image](https://github.com/vpenades/SharpGLTF/assets/3412782/009aa38a-c148-4c56-a041-da0bfd16d01b)

In `Image._WriteToSatellite`, when calling `System.IO.Path.ChangeExtension` method by a `FileNameWithoutExtension`, it will use the last `dot` symbol as the Separator between the `FileNameWithoutExtension` and `Extension`
![image](https://github.com/vpenades/SharpGLTF/assets/3412782/469e5f57-1afd-4eeb-bb3c-ffc46e87de4c)

**Comment by vpenades** [comment]
will look into it...
