### ISSUE TITLE
No tag for the alpha0031 release from nuget.org

### ISSUE THREAD

**Issue by gregmarr** [vpenades/SharpGLTF#229]
There is an alpha0031 release on nuget.org but no tag in the repo for it.

**Comment by vpenades** [comment]
Yes, I know, version 31 had so many changes that I wanted to write a proper changelog, but then time keeps slipping away, ultimately I'll probably publish a bare bones tag

I've been looking for a way to automate the generation of change logs, but all services seem to be paid

**Comment by gregmarr** [comment]
Thanks.  I was surprised to see it show up in my nuget updates because I'd been watching the tags page for the release.  :)

Thank you for providing the library.  It's a great help.
