### ISSUE TITLE
Support for EXT_meshopt_compression

### ISSUE THREAD

**Issue by famda** [vpenades/SharpGLTF#240]
Hi,

I'm trying to load a model that was compressed by [gltfpack](https://meshoptimizer.org/gltf/) without success.
I'm able to load the same model using babylon or threejs.

Is it supported?

Thanks!

**Comment by vpenades** [comment]
No, EXT_meshopt_compression is not supported.

see https://github.com/vpenades/SharpGLTF/discussions/235
