### ISSUE TITLE
Validation causes very long loading times and `Validation = Skip` does not help 

### ISSUE THREAD

**Issue by BoyBaykiller** [vpenades/SharpGLTF#245]
I was trying to load a converted [glTF model](https://drive.google.com/file/d/1fzgD-H0bMo5qUTp9VDoHjy1ewa0C31bA/view) from the newly released [CoD Caldera data set](https://github.com/Activision/caldera).

It takes SharpGLTF 55 seconds to load the file with `Validation = Skip`. Turns out of all the time is spent in this validation step (the model has 152.563 nodes):
https://github.com/vpenades/SharpGLTF/blob/c71bf2c536348569772dc469f81bf07cd23b865c/src/SharpGLTF.Core/Schema2/gltf.Scene.cs#L93-L97

After commenting it, loading time went down to 1500ms! I decided to also disable validation [here](https://github.com/vpenades/SharpGLTF/blob/c71bf2c536348569772dc469f81bf07cd23b865c/src/SharpGLTF.Core/Schema2/Serialization.ReadContext.cs#L303-L323) and that brought it down to 1050ms.

I'd be nice if `Validation = Skip` does not perform costly validation, or perhaps no Validation at all.

**Comment by vpenades** [comment]
I'll look into it

**Comment by deccer** [comment]
We used Blender's USD Import and GLTF Export. Be aware exporting might take "ages"
