### ISSUE TITLE
VBTexture1 not found

### ISSUE THREAD

**Issue by DimplesHei** [vpenades/SharpGLTF#248]
SharpGLTF.Ext.3DTiles  Samples,  Writing a 3D Tiles glTF file with texture metadata, 
var mesh = VBTexture1.CreateCompatibleMesh("mesh");
VBTexture1 not found.

**Comment by bertt** [comment]
add

```
using VBTexture1 = VertexBuilder<VertexPosition, VertexTexture1, VertexEmpty>;
```

**Comment by DimplesHei** [comment]
thank you
