### ISSUE TITLE
How to merge gltf and bin into one file

### ISSUE THREAD

**Issue by DimplesHei** [vpenades/SharpGLTF#251]
SaveGltf, How to merge gltf and bin into one file.

**Comment by vpenades** [comment]
If you want to convert gltf+bin to GLB:

use `.SaveGLB`  instead of `.SaveGLTF`  or use the .GLB extension in the file when saving

**Comment by DimplesHei** [comment]
use .SaveGLTF   can I save only one file .gltf? Merge bin into gltf?

**Comment by vpenades** [comment]
glTF has two modes:
- GLTF: multiple files (.gltf and .bin)
- GLB: single file (.glb)

So if you want a single file, you must use .GLB

**Comment by DimplesHei** [comment]
thanks.
