### ISSUE TITLE
How to convert multiple gltf files into 3dtiles?

### ISSUE THREAD

**Issue by DimplesHei** [vpenades/SharpGLTF#252]
How to convert multiple gltf into a single 3dtiles format?

**Comment by bertt** [comment]
you need a tileset.json file referencing the glTF's, for a sample see https://bertt.wordpress.com/2022/02/20/cesium-3d-tiles-model-placement/

**Comment by DimplesHei** [comment]
Can it be implemented using the SharpGltf ?

**Comment by DimplesHei** [comment]
thanks
