### ISSUE TITLE
Changing parents of nodes, removing nodes

### ISSUE THREAD

**Issue by mushroom-guy** [vpenades/SharpGLTF#253]
Hi! I was wondering if it's possible to change the parent of a node or to remove nodes altogether.

**Comment by vpenades** [comment]
yes and no...

glTF is not an authoring format, which means it's not meant to be editable.

At first sight changing parents or removing nodes may seem a trivial operation, but it has huge implications within the glTF architecture that are very hard to handle correctly.

My recomendations are:
- if they changes you want to do are minimal, you can fork the library and expose the internal methods or properties to support what you need.
- For bigger edition changes, my current suggestion is to convert the model to a SceneBuilder (in the toolkit) do all the editing there, and convert back to glTF

SceneBuilder is meant to be editable, but -it is not- a 100% clone of the original glTF model.

**Comment by mushroom-guy** [comment]
Thanks, I might go with the first one since I don't plan to do big changes
