### ISSUE TITLE
Provide an API for users who don't know the glTF API

### ISSUE THREAD

**Issue by naikrovek** [vpenades/SharpGLTF#26]
A simpler (and limited) API surface for users who do not know glTF should be provided for usability.

A user should be able to provide a list of vertices, zero or more materials, textures, and triangles, and be able to get a glTF file without further interaction with your API.

This API surface should be limited; there are only so many things that such an API would make sense for, to me.  Animation would not be supported, and clearly static meshes would.  

I don't know if this is within the scope of this API, and I wanted to suggest this in case it is.

**Comment by vpenades** [comment]
I think what you're looking for is the **MeshBuilder<>** class, which is included in the Toolkit package, in SharpGLTF.Geometry namespace.

This is a minimal example of how to create a triangle scene:

```c#
using SharpGLTF.Scenes;
using SharpGLTF.Geometry;
using SharpGLTF.Geometry.VertexTypes;
using SharpGLTF.Materials;

...

// Create a mesh with a triangle.
var mesh = new MeshBuilder<VertexPosition>();
var prim = mesh.UsePrimitive(MaterialBuilder.CreateDefault());

prim.AddTriangle
   (
   new VertexPosition(0, -1, 0), 
   new VertexPosition(1, 0, 0),
   new VertexPosition(0, 1, 0)
   );

// Create a scene and add the mesh:

var scene = new SceneBuilder();

scene.AddMesh(mesh, Matrix4x4.Identity);

// save it to GLB:

scene.ToSchema2().Save("scene.glb");
```

let me know if this is what you're looking for, or you need something different.

**Comment by naikrovek** [comment]
Excellent, thank you!  I'll close this.
