### ISSUE TITLE
Valid MorphPrimitivesTest.glb file fails to load

### ISSUE THREAD

**Issue by gleblebedev** [vpenades/SharpGLTF#28]
Repro steps:
Get the file from kronos samples
glTF-Sample-Models\2.0\MorphPrimitivesTest\glTF-Draco\MorphPrimitivesTest.glb

ModelRoot.Read throws an exception:
SharpGLTF.Validation.SchemaException: 'Accessor[0] Accessor[0]BufferView must be defined.'

It fails on version 1.0.0-alpha0013

**Comment by gleblebedev** [comment]
still fails on  1.0.0-alpha0014

**Comment by vpenades** [comment]
I'm afraid Draco compression is not supported yet, as it requires the native Google's Draco libraries.
