### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by promontis** [vpenades/SharpGLTF#3]
Hi @vpenades!

Could you update nuget package with the changes you have made recently?
Would love to use the mesh builder additions :)

**Comment by vpenades** [comment]
Hi @promontis 

I'm polishing some of the remaining bits, hopefully I'll update the packages soon.

The bits I'm working on right now are:

Materials and textures:
- There's some enumerations that need to be clarified.
- Clarify how to define a fallback material; right now there's no API for that.
- Texture Transform needs to be clarified; at first sight it looks like a general transform, but it seems it's intended to be used as a sort of Atlas selector.

Extras property:
- This is a nightmare, it's essentially an "anything goes" field, and it's difficult to come with an easy to use API.

Mesh builder:
- More documentation.
- Figuring out how to handle morph targets, or at least, ensure the current API will not prevent implementing morph targets in the future.

Notice I'm going to change package names.

So, SharpGLTF Alpha 0004 will be deprecated in favour of:

SharpGLTF.Core Alpha 0005
SharpGLTF.Toolkit Alpha 0005

Additionally, If you have any issue, or there's something in the API you don't like, let me know... feedback is important at this stage.

In the mean time, expect sudden API changes as usual... I'm still not happy with the look of some parts.

**Comment by vpenades** [comment]
@promontis I'm finishing the last bits of the API, I would ask you to do a review of the code just in case you see something odd.

After updating the packages, I'll probably focus on adding more tests and documentation for a while.

**Comment by vpenades** [comment]
@promontis I've just updated the packages.

I would suggest to replace the old package with this one: https://www.nuget.org/packages/SharpGLTF.Toolkit

Since it includes all the nice bits like the MeshBuilder.

**Comment by vpenades** [comment]
@promontis I've Just uploaded a new nuget package with the latest changes.

For my own needs, the API is more or less ready to use... I didn't receive much feedback of what other developers might need, so from now on I will focus on adding and improving unit tests, documentation and minor bug fixes.
