### ISSUE TITLE
WinUI3.0 control?

### ISSUE THREAD

**Issue by GeorgeS2019** [vpenades/SharpGLTF#30]
A few months back, I proposed the need for 3D model WinUI 3.0 control and it seems there is similar initiative at Microsoft focusing on glTF

It seems you have done that with [skeletal and morph animation](https://github.com/windows-toolkit/SceneLoader/issues/8#issuecomment-559782437) with Mono for desktop.
Is is possible to port to [WinUI compatible control?](https://github.com/windows-toolkit/SceneLoader)

**Comment by vpenades** [comment]
I have no knowledge of WinUI API, but if it has a mesh that supports multiple vertex formats, and its internal shader model supports skinned vertices, at the very least, skeletal animations could be supported.

**Comment by GeorgeS2019** [comment]
[WinUI3.0 [roadmap ](https://github.com/microsoft/microsoft-ui-xaml/issues/717)just started](https://docs.microsoft.com/en-us/uwp/toolkits/winui3/)
