### ISSUE TITLE
is invalid or does not exist. (Parameter 'dirPath')

### ISSUE THREAD

**Issue by bertt** [vpenades/SharpGLTF#32]
When upgrading from Alpha-0014 to Alpha-0015 I see a new error on saving GLB with ModelRoot.SaveGLB: 'is invalid or does not exist. (Parameter 'dirPath')'
The model contains a ChannelImage I think it could be related.

Tried to add the image using a fully specified path (instead of relative path), but same error occurs.

**Comment by vpenades** [comment]
I did a fast search and most "dirPath" uses are related to using Guard.DirectoryPathMustExist , which is a requirement... I assume you've already chekced the directory exists.

Could you give me a bit more context?

**Comment by bertt** [comment]
ok I'll try to create a small repro

**Comment by bertt** [comment]
Couldn't reproduce it quickly in almost identical code... Anyway, alpha-0015 solved another problem so good work :-)
