### ISSUE TITLE
Example1 seems to use an older version of the api

### ISSUE THREAD

**Issue by marcuslindh** [vpenades/SharpGLTF#34]
I can't make it work, Is there one example that is updated?

**Comment by vpenades** [comment]
That's right, I forgot to update this example with the new APIs.

I'm in the process of refactoring the internal validation system to align it with gltf_validator, which is taking a while...  but I'll see if I can fix the example by next week.

Thanks for reporting the issue!

**Comment by vpenades** [comment]
I've updated the project to the latest version; let me know if it works now.
