### ISSUE TITLE
Validation before write

### ISSUE THREAD

**Issue by torokze** [vpenades/SharpGLTF#42]
Hi,

There should be a way to select the validation strictness before write because it is so slow.
Something similar like during read. I wrote a gltf export for Revit and I have models to take more than an hour export time.

Thnx
Zolee

**Comment by vpenades** [comment]
I could add a property to disable validation when writing...

Although I would recomend not disabling validation: There's still a large number of issues with glTF in general, and the only way to know it is through validation.

**Comment by torokze** [comment]
Validation is good during the development to produce proper gltf. After that it's not unnecessary but skippable.

**Comment by vpenades** [comment]
I've just added a Validation property into WriteSettings, so you can disable validation when writing setting it to "Skip".

It will be available on the next nuget package release. I hope this will improve write performance a bit.

**Comment by torokze** [comment]
Thnx!!

I've already commented out for the release. After I validated all my buffers, bufferviews and accessors.
It is a huge performance boost.

Thnx again.
