### ISSUE TITLE
pbrSpecularGlossiness sample?

### ISSUE THREAD

**Issue by bertt** [vpenades/SharpGLTF#45]
Hi, is there maybe an example available how to use pbrSpecularGlossiness shaders? For example to create 'best practice' json https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness#best-practices 

```
{
    "materials": [
        {
            "name": "gold",
            "pbrMetallicRoughness": {
                "baseColorfactor": [ 1.0, 0.766, 0.336, 1.0 ],
                "roughnessFactor": 0.1
            },
            "extensions": {
                "KHR_materials_pbrSpecularGlossiness": {
                    "diffuseFactor": [ 0.0, 0.0, 0.0, 1.0 ],
                    "specularFactor": [ 1.0, 0.766, 0.336 ],
                    "glossinessFactor": 0.9
                }
            }
        }
    ]
}
```

**Comment by vpenades** [comment]
If you're using the Toolkit's MaterialBuilder framework, you can set a fallback material.

So let's say you want to create a material that has a main "specular glossiness" material, and a "metallic roughness" fallback material that will be used if specular glossiness is not available.

```c#
var fallback = new Materials.MaterialBuilder("material1 fallback")
                .WithMetallicRoughnessShader();

var primary = new Materials.MaterialBuilder("material1 primary")
                .WithSpecularGlossinessShader()
                .WithFallback(fallback) // sets "fallback" material for this material.
```

And then you use the "primary" material with MeshBuilders.

There's also a unit test [here](https://github.com/vpenades/SharpGLTF/blob/2d071e2a846e07e49b1703ce76719c3b38ede8bb/tests/SharpGLTF.Tests/Schema2/Authoring/ExtensionsCreationTests.cs#L55).

**Comment by bertt** [comment]
ok good tip, didn't know about the Fallback option.  Should I use WithChannelParam() for specifying the diffuseFactor, specularFactor and glossinessFactor ?

**Comment by vpenades** [comment]
Yes, you can follow [this chart](https://github.com/vpenades/SharpGLTF/tree/master/src/SharpGLTF.Toolkit/Materials) for filling the channel parameters.

**Comment by bertt** [comment]
One question about using EmissiveFactor, when I do:

```
            var material1 = new MaterialBuilder()
                .WithDoubleSide(true)
                .WithMetallicRoughnessShader()
                .WithChannelParam(KnownChannel.BaseColor, new Vector4(0.7f, 0, 0f, 1.0f))
                .WithEmissive(new Vector3(0.2f, 0.3f, 0.1f));
```

Result glTF is:

```
      "emissiveFactor": [
        1,
        1,
        1
      ],
```

I'm expecting 0.2, 0.3, 0.1 here. Same behaviour when doing:

```
.WithChannelParam(KnownChannel.Emissive, new Vector4((float)0.2, (float)0.3, (float)0.1, (float)0));
```

**Comment by vpenades** [comment]
It might be a bug.... checking on it...

**Comment by bertt** [comment]
ok thanks for looking into it!

**Comment by vpenades** [comment]
I've commited some improvements and API changes... the whole MaterialBuilder framework was more buggy than I expected, so I had to rewrite some code. I'm still not 100% not confident, so I'll keep writing more unit tests for a few days before uploading new packages.

In the meantime, if you could use the latest changes directly, it could help me identify any other bug or use case.

**Comment by bertt** [comment]
ok I've tested the above case with the latest MaterialBuilder code and it works now as expected :-)
