### ISSUE TITLE
Ability to get path of images

### ISSUE THREAD

**Issue by garrynewman** [vpenades/SharpGLTF#47]
When loading a model I want to be able to get the raw path of the image and load it myself, manually. With the current implementation I can't see a way to do that.

**Comment by vpenades** [comment]
This is by design, to simplify textures loading. this issue has also been discussed [here](https://github.com/vpenades/SharpGLTF/issues/27).

Keep in mind that textures can be stored in three different ways, so if you want to load the textures on your own, you must implement the three ways.

In particular, embedded and buffered textures would require you to write quite a lot of code to load the textures.

In the future, in order to use glTFs for runtime visualization, I am planning to add a load hook that will allow you to receive the images as they're loaded, so you can instantiate the GPU textures, without using additional memory, but I have no time estimation for this.

**Comment by garrynewman** [comment]
I can understand this, and it's nice and clean like the rest of the API.

From my POV I'm loading the model into another engine. So I want to load the model then create my own materials if they're not already on disk. To do this I need to be able to get the texture and either save it to disk if it's not already a satellite, or just write the name of the texture if it is.

I get that it adds complication and you don't want to muck the API up, but maybe it could be an extension method that accesses internal fields, hidden behind a .Advanced namespace or something?

As it is I have to use reflection to access _uri on the Image.

**Comment by vpenades** [comment]
Just to be clear.... 

You just want to get the name of the texture file _in case it's an external/satellite file_ but you'll load the embedded and buffered textures using the API...

Or you want to load _and_ decode all the textures on your own, which includes finding the bufferview and decoding the Mime64 text for embedded textures?

Right now after loading the texture into memory, I clear the _uri to avoid mis management, but I could do some tricks and expose it in another way. That would include checking that the _uri is not an embedded texture (in which case it would be cleared)

**Comment by garrynewman** [comment]
My engine process would be this

- Load the model
- Look for "<materialname>.mat" next to the model
- If on disk material doesn't exist, create it
- If it does, load it

To write the material I want to know whether the texture is on disk. That way I can make my material load the textures straight from the disk instead of re-routing through the model.

This is just so it works in my generic model/material/shader/texture system, which also supports other model formats.

**Comment by vpenades** [comment]
Okey, so if I understood correctly, you only need to handle the case where the texture is an external file, and when it's not, you'll load it through the proper API.

If that's the case, and given that's a feature that's been already requested, I'll figure out a way of exposing it in the API.

**Comment by garrynewman** [comment]
<3

**Comment by vpenades** [comment]
Okey, in the latest update, I've redesigned some of the Image APIs.... now most of the workload is inside MemoryImage.

You have a property called SourcePath that will point to the texture in the file system.

Notice this value will be Null if the image has been loaded from any source other than the file system.

**Comment by garrynewman** [comment]
<3 thank you!
