### ISSUE TITLE
Is there a way to add normal information while using PrimitiveBuilder.AddTriangle method?

### ISSUE THREAD

**Issue by Imaver** [vpenades/SharpGLTF#5]
Hi vpenades,

Could you please kindly let me know if there is a way to add normal information while using
PrimitiveBuilder.AddTriangle method?

I tested code from your examples and it worked perfectly with AddTriangle method.
However, when I am trying to create Vertex with VertexPositionNormal component and pass it to AddTriangle method, it is not working at the moment. 
3d models look good, but normal information is not there. I also tried to add some obvious 0,0,1 vectors to check if normal information is transferred, there were no visual changes.

Please refer to the attached file for code example.

If I am doing it wrong, could you please let me know how I can specify the normal information using AddTriangle method with a somewhat similar approach?
[TestGltf.txt](https://github.com/vpenades/SharpGLTF/files/3170469/TestGltf.txt)

I am not sure if this is an issue but have no other way to reach you. Your help is very much appreciated.

**Comment by vpenades** [comment]
You can create vertices with normals in this way:

using Geometry.VertexTypes;

var a = new VertexPositionNormal(new Vector3(0,0,10), new Vector3(0,0,1));
var a = new VertexPositionNormal(new Vector3(0,0,10), new Vector3(0,0,1));

**Comment by Imaver** [comment]
Thank you very much for the extensive explanation!
