### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by bertt** [vpenades/SharpGLTF#51]
Hi, is there a simple sample for getting started with animations? Like moving a box or so. I've looked in the unit tests but couldn't find it so quickly.

**Comment by vpenades** [comment]
Here's a good starting point:

https://github.com/vpenades/SharpGLTF/blob/8165fb67a3311bc37fd62bc4042351489d45433e/tests/SharpGLTF.Toolkit.Tests/Scenes/SceneBuilderTests.cs#L44

**Comment by bertt** [comment]
ok thanks, got that one working. I only see 'WithPoint' there?

**Comment by vpenades** [comment]
Ah, yes, WithPoint.  It just happens the same curve code is used for translation, animation and scaling, so it has the same method name for the three. I guess it makes more sense "WithKey" or something like that.
