### ISSUE TITLE
How to get the mesh bones ?

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [vpenades/SharpGLTF#62]
Hi there,

I don't how to get the bones (associated joints) of a specific mesh. I can get the all joints but not the relationship with meshes (once a skinned model is loaded ..)

Thank in advance,
Eric

**Comment by vpenades** [comment]
Given a specific Node, if it has a Mesh, and it's skinned, it will also contain a Skin.

The Skin object has an array of joints (and the corresponding inverse bind matrices) needed for skinning.
