### ISSUE TITLE
Null Reference when calling MeshPrimitive.Material

### ISSUE THREAD

**Issue by thatcosmonaut** [vpenades/SharpGLTF#63]
Hello, first off, thanks for the excellent library.

I am having an issue obtaining a reference to a material from a mesh primitive.

To reproduce:

- Load a model using SharpGLTF.Schema2.ModelRoot.ReadGLB(stream)
- Obtain a primitive from the model
- Calling `myPrimitive.Material` will crash with the error `System.NullReferenceException: Object reference not set to an instance of an object`

**Comment by vpenades** [comment]
Yes, this is fine.

As stupid as it sounds, glTF specification allow primitives without a material being assigned to them.

So you always need to check for null before using the material. If you find a null material you must interpret it as a "default" material.

**Comment by thatcosmonaut** [comment]
Well, that's unfortunate. Thanks for the clarification!
