### ISSUE TITLE
How to pass indices to a Mesh Primitive

### ISSUE THREAD

**Issue by Crauzer** [vpenades/SharpGLTF#64]
I'm converting a model to the glTF format but I can't seem to find how to pass vertex indices to a `PrimitiveBuilder`.
The `AddXXXXX` functions return the indices of the added triangle/point/w.e which seems like a very weird design choice to me.

**Comment by vpenades** [comment]
You don't, Indices are generated internally by Mesh and Primitive builders.

Given you have sourceVertices[] and sourceIndices[], you just do:

```
var a = sourceVertices[ sourceIndices[i0] ];
var b = sourceVertices[ sourceIndices[i1] ];
var c = sourceVertices[ sourceIndices[i2] ];
Builder.AddTriangle( a, b, c);
```

And the builder handles creating an internal collection of unique vertices and the corresponding index list.

**Comment by Crauzer** [comment]
Thanks for the help, I managed to convert the model properly. 👍🏼
