### ISSUE TITLE
How to download alpha0018 version's source code?

### ISSUE THREAD

**Issue by 674019130** [vpenades/SharpGLTF#66]
Hi.

I wonder where to download the **alpha0018** version's source code, cause when I download the code by `https://github.com/vpenades/SharpGLTF.git`, there are some errors.

Thanks. :-)

**Comment by vpenades** [comment]
you have download errors?  or the downloaded source code gives you errors when you compile?

**Comment by 674019130** [comment]
> you have download errors? or the downloaded source code gives you errors when you compile?

Sry for my poor English, it's when I compile the source code gives me errors. And now I'm using `alpha15` version.
I mean, the current source code maybe has some errors.

Thanks for your reply. Have a good day. 😊

**Comment by vpenades** [comment]
The source code requires Visual Studio 2019 to compile.

Which errors gives you?

**Comment by 674019130** [comment]
> The source code requires Visual Studio 2019 to compile.
> 
> Which errors gives you?

There's an embarrassing situation occurs... When I download the latest source code and build the project, no errors anymore...

The errors in last time is `can't find .NET Framework 4.5.1`, but I'm sure that my PC has installed `.NET Framework 4.5.1`.
Anyway, my puzzle has been solved.
Sry to occupy your time, may you...happy😃

**Comment by vpenades** [comment]
That's probably the Monogame Example, which requires net framework 4.5.1 for backwards compatibility.

But that's not a bug, that's missing frameworks in your development environment.

**Comment by 674019130** [comment]
> That's probably the Monogame Example, which requires net framework 4.5.1 for backwards compatibility.
> 
> But that's not a bug, that's missing frameworks in your development environment.

You are right, I will describe my question clearly next time.
Thanks for your patient reply again. ❤
