### ISSUE TITLE
Poor performance when creating Animations

### ISSUE THREAD

**Issue by Crauzer** [vpenades/SharpGLTF#71]
I'm bundling together a glTF file that includes a rigged model and a lot of animations (around 60).

This is the code that performs extremely poorly:
```
foreach((string animationName, LeagueAnimation leagueAnimation) in leagueAnimations)
{
    GltfAnimation animation = root.UseAnimation(animationName);

    foreach(AnimationTrack track in leagueAnimation.Tracks)
    {
        Node joint = joints.FirstOrDefault(x => Cryptography.ElfHash(x.Name) == track.JointHash);

        animation.CreateTranslationChannel(joint, track.Translations);
        animation.CreateScaleChannel(joint, track.Scales);
        animation.CreateRotationChannel(joint, track.Rotations);
    }
}
```

I've debugged this issue and came to the conclusion that the time it takes to execute a loop increases with the number of animations already added.

The first animation takes around `50ms` to create. After 10 loops the time increases to around `1300ms`.
Note that the size of the animations being converted does not increase.

I haven't debugged the internal code of the library yet, so I cannot conclude what exactly is taking so much time to do.

**Comment by vpenades** [comment]
Hmm... I've never created a test that exports that many animations, so there's probably some redundancy inside the library.

Do you have public source code that I can use for testing?

Btw, if you're converting some other format to glTF, I would suggest to use the Toolkit's SceneBuilder, it has a somewhat different API, but it's more comfortable to use when you're used to it.

**Comment by Crauzer** [comment]
[This](https://github.com/LoL-Fantome/Fantome.Libraries.League) is my library that works with some file formats from a game.

There is a [project](https://github.com/LoL-Fantome/Fantome.Libraries.League/tree/master/Fantome.Libraries.League.Tests) in there that has the (code)[https://github.com/LoL-Fantome/Fantome.Libraries.League/blob/master/Fantome.Libraries.League.Tests/Program.cs#L27] relevant to this issue.

These are the files you will need for testing:
[TestingFiles.zip](https://github.com/vpenades/SharpGLTF/files/5157271/TestingFiles.zip)

Only thing you will need to change is where the animations are being loaded from.

**Comment by vpenades** [comment]
Well... it seems it's going to be quite complex, so I'll try to take a look at it anytime this week
