### ISSUE TITLE
How to add normal info and texture info to one VERTEX?

### ISSUE THREAD

**Issue by 674019130** [vpenades/SharpGLTF#75]
Hi!

Now I came across a question:
 
`VertexTypes` only contains `VertexPositionNormal`, `VertexColor1Texture2` etc.

I can't add normal info and texture info to the same VERTEX.

Is there any solution?

Thx a lot, have a good day : )

**Comment by vpenades** [comment]
vertex types are designed so they can be _combined_.

for example:

```c#
var vertex = new VertexBuilder<VertexPositionNormal, VertexColor1Texture2 , VertexEmpty>();
```

**Comment by 674019130** [comment]
> vertex types are designed so they can be _combined_.
> 
> for example:
> 
> ```cs
> var vertex = new VertexBuilder<VertexPositionNormal, VertexColor1Texture2 , VertexEmpty>();
> ```

Thx for your patient reply : )
