### ISSUE TITLE
TrackBuilder does not support single point when using linear curve

### ISSUE THREAD

**Issue by ptasev** [vpenades/SharpGLTF#80]
I'm adding this issue to track what we discussed in Discord. I believe that linear curves according to the specification support having only 1 keyframe/point even though it doesn't make much sense.

Support for this should be added and, for the curve types that do not support only 1 point, add a guard higher up in the code so that it doesn't fail in the buffer view part of the code making the error obscure.

**Comment by vpenades** [comment]
The minimum number of keys was discussed [here](https://github.com/KhronosGroup/glTF/issues/185).

Still looking into it...

**Comment by vpenades** [comment]
Ok, I've confirmed this is a bug in one of the underlying functions of curve evaluation.. I'll fix it and also I'll take the time to add some documentation and argument valuation

**Comment by ptasev** [comment]
Excellent, thank you!
