### ISSUE TITLE
Hello there!

### ISSUE THREAD

**Issue by lz852153492** [vpenades/SharpGLTF#83]
I want to add the Extras attribute to Scenes and assign values to Extras. What should I do? I didn’t find a way to assign values

**Comment by vpenades** [comment]
Hi

It's been added recently to the development branch, the Alpha20 nuget package still doesn't support it.

In the developers branch the Extras property is implemented as a JsonContent which you can fill in a number of ways.

**Comment by vpenades** [comment]
Fixed in the new Alpha21 package.
