### ISSUE TITLE
BlendShape / MorphTarget

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [vpenades/SharpGLTF#86]
Hi there,

I would like to encode my own 3d asset with BlendShapes. I saw the `WithMorphTargetAccessors` but i don't know kow to convert my `IEnumerable<Vector3>` to `IEnumerable<MemoryAccessor>` and if it's the good way to do it ..
Help will be very appreciated ;)

Thank in advance,
Eric

**Comment by vpenades** [comment]
You could try to use WithMorphTargetAccessors, yes, but that's a very low level API that's only recomended if you know very well what are you doing, and you have a good understanding on glTF architecture.

The recomended way of creating or importing a mesh into glTF is by using the MeshBuilder API you can find in the toolkit library. MeshBuilder has an API to add morph targets, although it's a bit ugly.

You can find an example [here](https://github.com/vpenades/SharpGLTF/blob/ec7b07692cc9b4a5fcf8c166f0608491736e9f2a/tests/SharpGLTF.Toolkit.Tests/Scenes/SceneBuilderTests.cs#L383)

**Comment by GeorgeS2019** [comment]
@vpenades it would be great to have SharpGLTF showing how to do this [Blender Blend Shape](https://www.youtube.com/watch?v=ZJClHuIXRUM) - youtube tutorial [Sphere Mesh](https://github.com/EXPWorlds/Godot-Tutorials/blob/master/DaveTheDev%20Tutorials/11%20Using%20Shape%20Keys/Tutorial/Sphere.mesh) example. The mesh is available here, however, no Blender Sphere blend file.
