### ISSUE TITLE
modify material

### ISSUE THREAD

**Issue by FSandner** [vpenades/SharpGLTF#91]
Hi, i Love also this library, Great work!

Is there a way to modify; replace a material of a mesh or
IMeshBuilder<MaterialBuilder> mesh
object with a different color/material?

**Comment by vpenades** [comment]
It's not trivial; keep in mind that _the-material_ is used as a dictionary key so drawable primitives are _attached_ to that material, not the other way around. If I would allow, somehow, changing the current material of a primitive, you could be allowed to create a mesh with two primitive batches using the same material, which is not allowed.

The best solution right now is to copy the contents of a mesh to another mesh, applying a transform in the process.

**Comment by FSandner** [comment]
that's my problem...
i have the same geometry with a different color.
how can i copy this geometry to new Meshbuilder object?

**Comment by vpenades** [comment]
You create a new MeshBuilder (the destination), and you add your mesh to it with [this method](https://github.com/vpenades/SharpGLTF/blob/c542d65265a9f4d459abe8ecde67140dc25c5807/src/SharpGLTF.Toolkit/Geometry/MeshBuilder.cs#L191).

Notice that the method has a material converter lambda, so at that point you can inject your tit-for-tat material replacement.
