### ISSUE TITLE
How can get MeshContent from gltf file?

### ISSUE THREAD

**Issue by learnerandtrainer** [vpenades/SharpGLTF#95]
Hi ,
I have too many files created with SharpGLTF libraray. But some times I have to open them and read MeshContent. But when I want to cast to SharpGLTF.Scenes.MeshContent , the message says me its protected. there is any way to get content (geometries) of mesh
my code like below

```
string glbFile = fileUrl.Substring(0, fileUrl.LastIndexOf(".")) + ".glb";
  System.IO.File.WriteAllBytes(glbFile, b3dm.GlbData);
  var scene = SceneBuilder.Load(glbFile);
  var meshContent = ((SharpGLTF.Scenes.MeshContent)(scene.Instances[0]).Content.Content).Mesh;
```

**Comment by vpenades** [comment]
If you want to access the MeshBuilder, you don't need to cast MeshContent, you can get the mesh directly:

```c#
string glbFile = fileUrl.Substring(0, fileUrl.LastIndexOf(".")) + ".glb";
  System.IO.File.WriteAllBytes(glbFile, b3dm.GlbData);
  var scene = SceneBuilder.Load(glbFile);
  var mesh = scene.Instances[0].Content.GetGeometryAsset();
```

If what you need is to access to the MeshContent itself, let me know why you need it so I can figure out a solution

**Comment by learnerandtrainer** [comment]
thank you vpenades. I will try it

**Comment by learnerandtrainer** [comment]
thanks it worked
